# Generated by Django 3.1.4 on 2020-12-18 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20201207_1900'),
        ('desired', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='desired',
            unique_together={('movie',)},
        ),
    ]
