# Generated by Django 3.1.4 on 2020-12-06 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20201206_1044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Desired',
        ),
    ]
